### PR TITLE
Drop support for EOL Python 2.6

### LINKED ISSUE #175: Drop support for python 2.6?
I struggle to remember what's valid in all the different pythons, and thinking about it takes up time. It used to be worthwhile to support multiple versions of Python 2 while people moved between versions and when people relied on their system's python, but those days seem to be gone with everyone converging on Python 2.7 (Python 2.6 hasn't had an update since 2013; https://www.python.org/download/releases/2.6.9/). And it's not like we've kept supporting every version of Python 2 we ever used (we happily dropped 2.5, 2.4, ... etc in the past).

But please comment if you need param to keep working on Python 2.6...

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #175.

### CODE REVIEW

**Comment by ceball** [comment]
Thanks for following up comments with code :) The delay in responding is down to PR #202, opened just two days before this one, which ought to be merged first. Once that's finished, we'll move onto this...

**Comment by hugovk** [comment]
PR #202 is now merged, I've rebased this on master.

**Comment by ceball** [comment]
Thanks for updating your PR. I'd be happy for this to be merged, and I think it's ok for the next release of param not to support 2.6. 

(@jbednar, ok to merge, or do you see any problems?)

**Comment by jbednar** [comment]
Looks good; happy to see the end of 2.6!

**Pull request merged**
