### PR TITLE
Enabled cythonizing of param modules if Cython is available

### PR DESCRIPTION
**Pull request by philippjfr**
This small PR enables cythonizing for the param ``__init__``, ``parameterized`` and ``version`` modules. The IPython module has too much magic in it to be supported. Overall this already provides roughly a 50% speedup when creating new parameterized objects (measured by creating 20k HoloViews Images). In future we could go further and actually rewrite some parts of param as actual Cython, but I suspect that may not be worth it given the decent speedup without it and that most of the remaining time is spent deep copying default parameter values, which can in some cases be avoided by setting ``instantiate`` to ``False`` on a parameter.

### CODE REVIEW

**Comment by philippjfr** [comment]
Seems Python 3.2 isn't supported by the coverage tool anymore so it's failing. Will have to decide whether we should drop support for 3.2 as well.

**Comment by jbednar** [comment]
I think we can safely drop support for Python 3.2 from the latest Param release, or at least stop testing it.

**Comment by jbednar** [comment]
I'm happy for this to be merged.

**Comment by philippjfr** [comment]
Removed Python 3.2, tests are now passing. Ready to merge whenever.

**Pull request merged**
