### PR TITLE
WIP/demo: Make subscribers/watchers wait

### PR DESCRIPTION
**Pull request by ceball**
I started this some time ago at the end of doing the depends work to handle batching, but only just now made it into enough of a demo. The work in this PR is really not thought through (does the idea even make sense?), and isn't how I'd want it to be even if the idea makes sense, but the example might be enough to see if the idea is worthwhile pursuing or not...

Just make watchers wait (see "subscribers_wait" context manager at the end):

screen shot 2018-09-13 at 9 43 20 pm

Make watchers wait and process all changes together:

screen shot 2018-09-13 at 9 43 47 pm

### CODE REVIEW

**Comment by jlstevens** [comment]
This idea is closely related to something I need for #259 in `set_param` and I suspect this proposal is syntactic sugar for the same concept (personally, I would prefer parallel setting via `set_param` than using a context manager).

**Comment by ceball** [comment]
Yes, I guess I was kind of dumping this earlier start on you, for you to figure out and decide about ;)

**Comment by ceball** [comment]
(The idea came from seeing what traitlets and/or traits does, kind of, I think.)

**Comment by jlstevens** [comment]
This PR has some useful ideas to consider that can be implemented on top the initial batched watching  mechanism implemented here in #281. @ceball if you are happy with closing this PR, I can continue to refer to it as I further extend batched watching...

**Comment by philippjfr** [comment]
I think we can safely close. Can always resurrect any ideas from the branch.

**Pull request closed without merging**
